# Generated by Django 5.0.7 on 2024-08-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_personal_person_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
