# Generated by Django 5.0.7 on 2024-08-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
