# Generated by Django 5.0.7 on 2024-08-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('f', 'female'), ('m', 'male')], default='m', max_length=10),
        ),
    ]
