# Generated by Django 5.0.7 on 2024-08-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_pages_count_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default='13333'),
        ),
    ]
